// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/apex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceContext captures the state of the machine at the time of the crash.
type DeviceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	TotalMemory   int64                  `protobuf:"varint,3,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	FreeMemory    int64                  `protobuf:"varint,4,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	BatteryLevel  float32                `protobuf:"fixed32,5,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	IsCharging    bool                   `protobuf:"varint,6,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	NetworkType   string                 `protobuf:"bytes,7,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"` // e.g., "wifi", "cellular", "none"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceContext) Reset() {
	*x = DeviceContext{}
	mi := &file_proto_apex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceContext) ProtoMessage() {}

func (x *DeviceContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceContext.ProtoReflect.Descriptor instead.
func (*DeviceContext) Descriptor() ([]byte, []int) {
	return file_proto_apex_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceContext) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceContext) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceContext) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *DeviceContext) GetFreeMemory() int64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

func (x *DeviceContext) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *DeviceContext) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *DeviceContext) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

// CrashReport is the "DNA" of the error.
type CrashReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorId       string                 `protobuf:"bytes,1,opt,name=error_id,json=errorId,proto3" json:"error_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace    string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Context       *DeviceContext         `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	AiInsight     string                 `protobuf:"bytes,6,opt,name=ai_insight,json=aiInsight,proto3" json:"ai_insight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashReport) Reset() {
	*x = CrashReport{}
	mi := &file_proto_apex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashReport) ProtoMessage() {}

func (x *CrashReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashReport.ProtoReflect.Descriptor instead.
func (*CrashReport) Descriptor() ([]byte, []int) {
	return file_proto_apex_proto_rawDescGZIP(), []int{1}
}

func (x *CrashReport) GetErrorId() string {
	if x != nil {
		return x.ErrorId
	}
	return ""
}

func (x *CrashReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CrashReport) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *CrashReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CrashReport) GetContext() *DeviceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CrashReport) GetAiInsight() string {
	if x != nil {
		return x.AiInsight
	}
	return ""
}

// BatchReport allows us to squeeze multiple errors into one sync.
type BatchReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*CrashReport         `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReport) Reset() {
	*x = BatchReport{}
	mi := &file_proto_apex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReport) ProtoMessage() {}

func (x *BatchReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReport.ProtoReflect.Descriptor instead.
func (*BatchReport) Descriptor() ([]byte, []int) {
	return file_proto_apex_proto_rawDescGZIP(), []int{2}
}

func (x *BatchReport) GetReports() []*CrashReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

var File_proto_apex_proto protoreflect.FileDescriptor

const file_proto_apex_proto_rawDesc = "" +
	"\n" +
	"\x10proto/apex.proto\x12\x04apex\"\xe0\x01\n" +
	"\rDeviceContext\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12!\n" +
	"\ftotal_memory\x18\x03 \x01(\x03R\vtotalMemory\x12\x1f\n" +
	"\vfree_memory\x18\x04 \x01(\x03R\n" +
	"freeMemory\x12#\n" +
	"\rbattery_level\x18\x05 \x01(\x02R\fbatteryLevel\x12\x1f\n" +
	"\vis_charging\x18\x06 \x01(\bR\n" +
	"isCharging\x12!\n" +
	"\fnetwork_type\x18\a \x01(\tR\vnetworkType\"\xcf\x01\n" +
	"\vCrashReport\x12\x19\n" +
	"\berror_id\x18\x01 \x01(\tR\aerrorId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12-\n" +
	"\acontext\x18\x05 \x01(\v2\x13.apex.DeviceContextR\acontext\x12\x1d\n" +
	"\n" +
	"ai_insight\x18\x06 \x01(\tR\taiInsight\":\n" +
	"\vBatchReport\x12+\n" +
	"\areports\x18\x01 \x03(\v2\x11.apex.CrashReportR\areportsB\x1fZ\x1dgithub.com/Segniko/Apex/protob\x06proto3"

var (
	file_proto_apex_proto_rawDescOnce sync.Once
	file_proto_apex_proto_rawDescData []byte
)

func file_proto_apex_proto_rawDescGZIP() []byte {
	file_proto_apex_proto_rawDescOnce.Do(func() {
		file_proto_apex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apex_proto_rawDesc), len(file_proto_apex_proto_rawDesc)))
	})
	return file_proto_apex_proto_rawDescData
}

var file_proto_apex_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_apex_proto_goTypes = []any{
	(*DeviceContext)(nil), // 0: apex.DeviceContext
	(*CrashReport)(nil),   // 1: apex.CrashReport
	(*BatchReport)(nil),   // 2: apex.BatchReport
}
var file_proto_apex_proto_depIdxs = []int32{
	0, // 0: apex.CrashReport.context:type_name -> apex.DeviceContext
	1, // 1: apex.BatchReport.reports:type_name -> apex.CrashReport
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_apex_proto_init() }
func file_proto_apex_proto_init() {
	if File_proto_apex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apex_proto_rawDesc), len(file_proto_apex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_apex_proto_goTypes,
		DependencyIndexes: file_proto_apex_proto_depIdxs,
		MessageInfos:      file_proto_apex_proto_msgTypes,
	}.Build()
	File_proto_apex_proto = out.File
	file_proto_apex_proto_goTypes = nil
	file_proto_apex_proto_depIdxs = nil
}
